name: shell commands

on: [push]

jobs:
    run-shell-command-ubuntu: 
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "hello world"
            - name: multipline script
              run: |
                  node -v
                  pip -V
                  npm -v
    run-shell-command-windows: 
        runs-on: windows-latest
        steps:
            - name: echo a string
              run: echo "hello world"
